# Generated by Django 5.1.1 on 2024-09-22 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0014_use_autofields_for_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarrelation',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_ca_content_cddadb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start', 'end'], name='schedule_ev_start_a258cb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrelation',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_ev_content_6ceecb_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['start', 'end'], name='schedule_oc_start_76a2f8_idx'),
        ),
    ]
